# much of this is taken from the Empress main.yml file and the Gemelli main.yml
name: Main CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: foo

      - name: Install conda reqs
        shell: bash -l {0}
        run: conda install --file ci/conda_requirements.txt -c biocore
      
      - name: Install DEBIAS-M
        shell: bash -l {0}
        run: pip install -e .

      - name: Run tests & coverage
        shell: bash -l {0}
        run: nosetests -v debiasm --with-coverage --cover-package= debiasm

